# Generated by Django 2.0.3 on 2018-03-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_log_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='log',
            name='history_name',
            field=models.CharField(default='Default Log Name', max_length=50),
        ),
    ]
